apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: efk
  region: us-east-1

nodeGroups:
  - name: efk-workers
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 30
    ssh:
      allow: true
      
